# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: XCrawler - Build & Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]

jobs:

  sonar_cloud:
    name: SonarCloud
    uses: ./.github/workflows/sonar_cloud.yml
    secrets: inherit

  security_check:
    name: Security check
    uses: ./.github/workflows/security_check.yml
    secrets: inherit

  #      - name: Psalm
  #        uses: docker://ghcr.io/psalm/psalm-github-actions
  #        with:
  #          security_analysis: true
  #          report_file: results.sarif
  #      - name: Upload Psalm Security Analysis results to GitHub
  #        uses: github/codeql-action/upload-sarif@v2
  #        with:
  #          sarif_file: results.sarif

  #  pint:
  #    name: Laravel Pint
  #    runs-on:
  #      - self-hosted
  #      - ubuntu
  #    steps:
  #      - name: Clean up .scannerwork folder
  #        run: sudo rm -rf .scannerwork

  #      - name: Laravel Pint
  #        uses: aglipanci/laravel-pint-action@2.0.0
  #        with:
  #          preset: laravel
  #          verboseMode: true
  #          testMode: true
  #          configPath: "./pint.json"
  #          pintVersion: 1.8.0

  code_standards:
    name: Code standards check
    needs: [ sonar_cloud, security_check ]
    uses: ./.github/workflows/code_standards.yml
    secrets: inherit

  tests:
    name: Execute UnitTest
    needs: [ code_standards ]
    uses: ./.github/workflows/unittest.yml
    secrets: inherit

  finalizing_build:
    name: "All Parallel Tests passed"
    needs: [ tests ]
    uses: ./.github/workflows/codecov.yml
    secrets: inherit
